=== BackupTheBerlios/ebooking/eBooking/src/ebooking/core/dtd/validator.dtd
<!--
    VALIDATORS ELEMENT DESCRIPTION

    The validator dtd defines all known validators
    used in an application. A validator element has the id and the class
    of the validator.

    Example:
        <validators>
            <validator id="required" class="wilken.openshop.validation.validator.RequiredValidator"/>
            .
            .
            .
        </validators>
 -->
<!ELEMENT validators (validator+)>

<!--
    VALIDATOR ELEMENT DESCRIPTION

    The validator element contains the attributes id and class.

    Example:
        <validator id="required" class="wilken.openshop.validation.validator.RequiredValidator"/>

        The id identifies the validator and the class attribute containing the classpath to
        the validator. All attributes are required.
 -->
<!ELEMENT validator EMPTY>

<!--
    VALIDATOR ATTRIBUTES DESCRIPTION

    Attributes of a validator element. See at VALIDATOR ELEMENT DESCRIPTION.
-->
<!ATTLIST validator
id      ID      #REQUIRED
class   CDATA   #REQUIRED
>

=== BackupTheBerlios/ebooking/eBooking/WEB-INF/classes/validators.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE validators SYSTEM "http://www.openshop.de/dtds/validator.dtd">

<validators>
    <validator id="required" class="wilken.openshop.validation.validator.RequiredValidator"/>
    <validator id="number" class="wilken.openshop.validation.validator.NumberValidator"/>
    <validator id="string" class="wilken.openshop.validation.validator.StringValidator"/>
    <validator id="regex" class="wilken.openshop.validation.validator.RegexValidator"/>
    <validator id="email" class="wilken.openshop.validation.validator.EmailValidator"/>
    <validator id="date" class="wilken.openshop.validation.validator.DateValidator"/>
    <validator id="expression" class="wilken.openshop.validation.validator.ExpressionValidator"/>
</validators>
